name: trigger-limit-test

on:
  workflow_dispatch:

jobs:
  fail-on-purpose:
    runs-on: self-hosted
    steps:
      - run: |
          echo "::error::hit rate limit exceeded, please retry later"
          exit 1
