name: trigger-limit-test

on:
  workflow_dispatch:

jobs:
  fail-on-purpose:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::error::The job was not started because recent account payments have failed or your spending limit needs to be increased. Please check the 'Billing & plans' section in your settings"
          exit 1
